In [1]:
import pandas as pd
import numpy as np

In [2]:
meta_data=pd.read_csv("otu_data/metadata_for_7452.tsv", sep="\t", )
meta_data

,Run_ID,BioProject,BioSample,Health_status,Phenotype,Full_Name,Sex,Age,Location,Sample,Platform,BMI,Author,Class_Label
0,ERR11004600,PRJEB36300,SAMEA112768770,NON-HEALTHY,AP,Acute Pancreatitis,NaN,NaN,China,Stool,Illumina HiSeq X,NaN,Liu et al,NaN
1,ERR11004601,PRJEB36300,SAMEA112768771,NON-HEALTHY,AP,Acute Pancreatitis,NaN,NaN,China,Stool,Illumina HiSeq X,NaN,Liu et al,NaN
2,ERR11004602,PRJEB36300,SAMEA112768772,NON-HEALTHY,AP,Acute Pancreatitis,NaN,NaN,China,Stool,Illumina HiSeq X,NaN,Liu et al,NaN
3,ERR11004603,PRJEB36300,SAMEA112768773,NON-HEALTHY,AP,Acute Pancreatitis,NaN,NaN,China,Stool,Illumina HiSeq X,NaN,Liu et al,NaN
4,ERR11004604,PRJEB36300,SAMEA112768774,NON-HEALTHY,AP,Acute Pancreatitis,NaN,NaN,China,Stool,Illumina HiSeq X,NaN,Liu et al,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7447,SRR6474313,PRJNA375935,SAMN08366191,HEALTHY,Healthy,Healthy,MALE,62.0,China,Stool,Illumina HiSeq 2000,20.58,Wen et al,NaN
7448,SRR6474314,PRJNA375935,SAMN08366198,HEALTHY,Healthy,Healthy,MALE,26.0,China,Stool,Illumina HiSeq 2000,22.73,Wen et al,NaN
7449,SRR6474315,PRJNA375935,SAMN08366197,HEALTHY,Healthy,Healthy,MALE,33.0,China,Stool,Illumina HiSeq 2000,19.59,Wen et al,NaN
7450,SRR6474316,PRJNA375935,SAMN08366196,HEALTHY,Healthy,Healthy,MALE,32.0,China,Stool,Illumina HiSeq 2000,19.24,Wen et al,NaN
7451,SRR6474317,PRJNA375935,SAMN08366195,HEALTHY,Healthy,Healthy,MALE,42.0,China,Stool,Illumina HiSeq 2000,21.75,Wen et al,NaN

In [3]:
training_otu_wihtoutcorrected=pd.read_csv("otu_data/without_corrected_otu_7452_species.csv", sep=",", index_col=0)
training_otu_wihtoutcorrected

,ERR11004600,ERR11004601,ERR11004602,ERR11004603,ERR11004604,ERR11004605,ERR11004606,ERR11004607,ERR11004608,ERR11004669,...,SRR6474308,SRR6474309,SRR6474310,SRR6474311,SRR6474312,SRR6474313,SRR6474314,SRR6474315,SRR6474316,SRR6474317
MGYG000003389,0,0,17,29,20,0,0,0,0,0,...,0,0,0,0,14,0,13,0,0,0
CADBRU01_sp900762815,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
MGYG000001768,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
UBA1436_sp900540405,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
UBA1436_sp002329395,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,116,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Ruminococcus_E_bromii_A,179,233,145,0,29,484,148,75,385,307,...,359,362,1357,14,516,424,330,1555,186,1006
Ruminococcus_E_sp003526955,42380,19309,99,27,48,107450,18175,178,12763,2311,...,607,270,171760,0,12188,390,975,3218,184,37325
Ruminococcus_E_sp003438075,7312,3607,466,332,240,23507,3922,409,104749,2878,...,1443,398,30826,138,5733,1695,8242,4254,632,7791
Ruminococcus_E_bromii,11179,6481,656,313,216,10968,3387,44,2175,12584,...,23014,10873,134862,70,64897,7399,48282,120966,4172,47731
Ruminococcus_E_bromii_B,32228,18221,1391,908,597,8260,8745,183,5035,36109,...,70987,33740,406729,211,210749,5706,156155,365520,12948,145779

In [9]:
training_corrected=pd.read_csv("otu_data/corrected_training_7452.csv", sep="\t", header=0, index_col=0, engine="c")
training_corrected

,ERR11004600,ERR11004601,ERR11004602,ERR11004603,ERR11004604,ERR11004605,ERR11004606,ERR11004607,ERR11004608,ERR11004669,...,SRR6474308,SRR6474309,SRR6474310,SRR6474311,SRR6474312,SRR6474313,SRR6474314,SRR6474315,SRR6474316,SRR6474317
MGYG000003389,0,0,8,11,12,0,0,0,0,0,...,0,0,0,0,17,0,31,0,0,0
CADBRU01_sp900762815,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
MGYG000001768,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
UBA1436_sp900540405,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
UBA1436_sp002329395,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,158,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Ruminococcus_E_bromii_A,317,335,207,0,84,476,160,181,413,440,...,1124,1150,3627,72,1193,954,1457,4238,493,2158
Ruminococcus_E_sp003526955,60750,22675,110,33,79,101631,15327,296,12249,2803,...,1122,519,357838,0,18768,500,2603,5981,301,59681
Ruminococcus_E_sp003438075,8323,3905,640,484,532,14540,2915,856,53996,3371,...,3329,1006,56162,388,9297,2812,24324,8831,1238,12031
Ruminococcus_E_bromii,14788,7206,722,350,353,9518,2736,87,2036,14344,...,65314,32350,340539,252,135859,15411,190307,316061,10344,98201
Ruminococcus_E_bromii_B,39198,19276,1628,1090,1063,7238,6894,381,4748,38003,...,164176,81085,882008,494,370725,9050,517102,820758,25782,251750

In [5]:
validation_without_corrected = pd.read_csv("otu_data/without_corrected_validation_OTU_642_samples.csv", sep=",", index_col=0)
validation_without_corrected

,ERR1018185,ERR1018186,ERR1018187,ERR1018188,ERR1018189,ERR1018190,ERR1018191,ERR1018192,ERR1018193,ERR1018194,...,SRR585752,SRR585753,SRR585756,SRR585757,SRR585760,SRR585762,SRR585764,SRR585765,SRR585781,SRR585786
MGYG000003389,0,0,0,10,22,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CADBRU01_sp900762815,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
MGYG000001768,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
UBA1436_sp900540405,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
UBA1436_sp002329395,34,0,56,12,36,0,0,27,15,0,...,0,11,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Ruminococcus_E_bromii_A,5362,4663,3773,15087,1287,1229,2319,62,968,95,...,795,30755,1559,1217,284,471,3287,1563,3356,1495
Ruminococcus_E_sp003526955,2793,297179,1596104,23527,619,1560,2102,276,447749,184,...,3009,518977,434162,1406,657,809,1289,1472,1622,5067
Ruminococcus_E_sp003438075,3682,2147305,269852,37373,2306,3687,10384,2760,57245,331,...,10257,90410,91637,4503,1687,3103,2001,2905,3337,24966
Ruminococcus_E_bromii,1052,7507,14938,1172879,33510,70668,193759,103,2164,12256,...,68483,26705,45438,60060,39693,1300,52783,104700,101203,310705
Ruminococcus_E_bromii_B,6843,5100,9384,3653113,99085,230322,529667,553,1006,38039,...,189670,5105,127511,174714,112648,2085,142373,322772,264021,850754

In [6]:
validation_corrected = pd.read_csv("otu_data/corrected_corrected_validation_OTU_642_samples.csv", sep=",", index_col=0)
validation_corrected

,ERR1018185,ERR1018186,ERR1018187,ERR1018188,ERR1018189,ERR1018190,ERR1018191,ERR1018192,ERR1018193,ERR1018194,...,SRR585752,SRR585753,SRR585756,SRR585757,SRR585760,SRR585762,SRR585764,SRR585765,SRR585781,SRR585786
MGYG000003389,0,0,0,24,46,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CADBRU01_sp900762815,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
MGYG000001768,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
UBA1436_sp900540405,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
UBA1436_sp002329395,60,0,101,26,66,0,0,44,28,0,...,0,35,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Ruminococcus_E_bromii_A,5349,3939,4214,12114,1728,1070,3049,127,1185,133,...,324,39708,611,725,65,111,959,422,1321,419
Ruminococcus_E_sp003526955,2277,194512,1305790,18371,536,882,2548,205,313411,139,...,466,249616,91051,302,58,69,107,134,191,543
Ruminococcus_E_sp003438075,3819,1312374,235781,33301,2554,2613,14010,2541,46526,323,...,3315,85136,40301,1398,223,398,215,324,521,5047
Ruminococcus_E_bromii,870,4898,12135,753975,25613,34801,192790,84,1568,7877,...,12821,6126,6272,12671,4194,47,5146,11479,14922,47405
Ruminococcus_E_bromii_B,4100,2601,6018,1889620,58367,88227,423719,307,569,18994,...,36469,668,18255,40255,12514,77,14117,37377,39060,128707

In [11]:
validation_metadata=pd.read_csv("otu_data/validation_metadata_642_samples.csv",sep=",")
validation_metadata

,Run_ID,BioProject,BioSample,Health_status,Phenotype,Full_Name,Sex,Age,Location,Sample,Platform,BMI,Author,Class_Label
0,ERR1018185,PRJEB10878,SAMEA3541469,NON-HEALTHY,CRC,Colorectal Cancer,MALE,64.0,China,Stool,Illumina HiSeq 2000,23.1,Yu et al,0
1,ERR1018186,PRJEB10878,SAMEA3541470,NON-HEALTHY,CRC,Colorectal Cancer,MALE,73.0,China,Stool,Illumina HiSeq 2000,23.8,Yu et al,0
2,ERR1018187,PRJEB10878,SAMEA3541471,NON-HEALTHY,CRC,Colorectal Cancer,FEMALE,67.0,China,Stool,Illumina HiSeq 2000,24.7,Yu et al,0
3,ERR1018188,PRJEB10878,SAMEA3541472,NON-HEALTHY,CRC,Colorectal Cancer,MALE,56.0,China,Stool,Illumina HiSeq 2000,25.6,Yu et al,0
4,ERR1018189,PRJEB10878,SAMEA3541473,NON-HEALTHY,CRC,Colorectal Cancer,FEMALE,59.0,China,Stool,Illumina HiSeq 2000,20.7,Yu et al,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
637,SRR585762,PRJNA177201,SAMN01760950,HEALTHY,Healthy,Healthy,FEMALE,70.0,Sweden,Stool,Illumina HiSeq2000,NaN,Karlsson et al.,1
638,SRR585764,PRJNA177201,SAMN01760976,HEALTHY,Healthy,Healthy,MALE,70.0,Sweden,Stool,Illumina HiSeq2000,NaN,Karlsson et al.,1
639,SRR585765,PRJNA177201,SAMN01760977,HEALTHY,Healthy,Healthy,MALE,71.0,Sweden,Stool,Illumina HiSeq2000,NaN,Karlsson et al.,1
640,SRR585781,PRJNA177201,SAMN01760978,HEALTHY,Healthy,Healthy,MALE,70.0,Sweden,Stool,Illumina HiSeq2000,NaN,Karlsson et al.,1
641,SRR585786,PRJNA177201,SAMN01760980,HEALTHY,Healthy,Healthy,MALE,70.0,Sweden,Stool,Illumina HiSeq2000,NaN,Karlsson et al.,1

In [12]:
import pandas as pd
import numpy as np
from skbio.stats.distance import DistanceMatrix
from skbio.stats.ordination import pcoa
from scipy.spatial.distance import pdist, squareform
import matplotlib.pyplot as plt
import matplotlib as mpl

In [ ]:
meta_data = pd.read_csv("otu_data/metadata_for_7452.tsv", sep="\t")
training_otu_wihtoutcorrected = pd.read_csv("otu_data/without_corrected_otu_7452_species.csv", sep=",", index_col=0)
training_corrected = pd.read_csv("otu_data/corrected_training_7452.csv", sep="\t", header=0, index_col=0, engine="c")
validation_without_corrected = pd.read_csv("otu_data/without_corrected_validation_OTU_642_samples.csv", sep=",", index_col=0)
validation_corrected = pd.read_csv("otu_data/corrected_corrected_validation_OTU_642_samples.csv", sep=",", index_col=0)
validation_metadata = pd.read_csv("otu_data/validation_metadata_642_samples.csv", sep=",")

print(meta_data.shape)
print(training_otu_wihtoutcorrected.shape)
print(training_corrected.shape)
print(validation_without_corrected.shape)
print(validation_corrected.shape)
print(validation_metadata.shape)

In [13]:
mpl.rcParams['pdf.fonttype'] = 42
mpl.rcParams['ps.fonttype'] = 42
mpl.rcParams['font.size'] = 11
mpl.rcParams['axes.titlesize'] = 12
mpl.rcParams['axes.labelsize'] = 11

In [14]:
def compute_pcoa(otu_table):
    sample_by_species = otu_table.T
    bc_dist = pdist(sample_by_species.values, metric='braycurtis')
    bc_dist_matrix = squareform(bc_dist)
    dm = DistanceMatrix(bc_dist_matrix, ids=sample_by_species.index)
    pcoa_results = pcoa(dm)
    return pcoa_results, sample_by_species.index

In [ ]:
pcoa_train_before, train_ids = compute_pcoa(training_otu_wihtoutcorrected)
pcoa_train_after, _ = compute_pcoa(training_corrected)
pcoa_val_before, val_ids = compute_pcoa(validation_without_corrected)
pcoa_val_after, _ = compute_pcoa(validation_corrected)

In [ ]:
meta_data_indexed = meta_data.set_index("Run_ID")
validation_metadata_indexed = validation_metadata.set_index("Run_ID")

train_batch = meta_data_indexed.loc[train_ids, "BioProject"]
val_batch = validation_metadata_indexed.loc[val_ids, "BioProject"]

train_health = meta_data_indexed.loc[train_ids, "Health_status"]
val_health = validation_metadata_indexed.loc[val_ids, "Health_status"]

In [ ]:
def plot_pcoa(ax, pcoa_result, batch_labels, title):
    coords = pcoa_result.samples.iloc[:, [0, 1]]
    unique_batches = batch_labels.unique()
    cmap = plt.cm.get_cmap('tab20', len(unique_batches))
    
    for i, batch in enumerate(unique_batches):
        mask = (batch_labels == batch).values
        ax.scatter(coords.iloc[mask, 0], coords.iloc[mask, 1],
                   alpha=0.65, s=18, color=cmap(i), edgecolors='none')
    
    var_exp = pcoa_result.proportion_explained
    ax.set_xlabel(f"PCo1 ({var_exp.iloc[0]*100:.2f}%)")
    ax.set_ylabel(f"PCo2 ({var_exp.iloc[1]*100:.2f}%)")
    ax.set_title(title, fontweight='bold')
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

In [ ]:
fig, axes = plt.subplots(2, 2, figsize=(14, 12), dpi=100)

plot_pcoa(axes[0,0], pcoa_train_before, train_batch,
          "Training Set — Before Batch Correction")
plot_pcoa(axes[0,1], pcoa_train_after, train_batch,
          "Training Set — After Batch Correction")
plot_pcoa(axes[1,0], pcoa_val_before, val_batch,
          "Validation Set — Before Batch Correction")
plot_pcoa(axes[1,1], pcoa_val_after, val_batch,
          "Validation Set — After Batch Correction")

plt.tight_layout()

In [ ]:
fig.savefig("PCoA_batch_correction_comparison.png", dpi=600, bbox_inches='tight')
fig.savefig("PCoA_batch_correction_comparison.pdf", bbox_inches='tight')
fig.savefig("PCoA_batch_correction_comparison.tiff", dpi=600, bbox_inches='tight')

plt.show()